const autores = {
  development: [
    ["Pilar Sordo", 0,1],
    ["E.D. Bulker", 1,2],
  ],
  testing: [
    ["Pilar Sordo", 0,1],
    ["E.D. Bulker", 1,2],
  ],
  production: [
    ["Pilar Sordo",1,1],
    ["E.D. Bulker",0,2],
    ["Jorge Luis Borges",1,3],
    ["Miguel Aloi",0,4],
    ["Isabel Allende",1,5],
    ["Gustavo Maine",0,6],
    ["Fernando Pessoa",1,7],
    ["Curley Kronsky",0,8],
    ["Mario Benedetti",1,9],
    ["Fernando Butazzoni",1,10],
    ["Maximiliano Collins",0,11],
    ["Diego Fischer",1,12],
    ["Alberto Lieberman",0,13],
    ["Jorge Kenner",0,14],
    ["Markus Zusac",0,15],
    ["Grant Morín",0,16],
    ["Carlos de María",0,17],
    ["Juan Rulfo",1,18],
    ["Suzanne Collins",1,19],
    ["Walter Dresel",0,20],
    ["Andrés Arch",0,21],
    ["Theodor. W. Roddes",0,22],
    ["Ireneo Batlle  Pizarnik",0,23],
    ["Frederick Forsyth",1,24],
    ["José Mauro de Vasconcelos",1,25],
    ["Paulina Zapata Lozano",0,26],
    ["Gabriel Rolón",1,27],
    ["Ricardo Fogel",0,28],
    ["Clara Ñuble",0,29],
    ["Dan Brown",1,30],
    ["Julio Cortázar",1,31],
    ["Rosa Len",0,32],
    ["Stephen King",1,33],
    ["Haruki Murakami",1,34],
    ["Mario Levrero",1,35],
    ["Alfonso de Guzmán",0,36],
    ["John Grisham",0,37],
    ["Paulo Coelho",1,38],
    ["Saul Buscema",0,39],
    ["Mario Delgado Aparaín",1,40],
    ["Jorge Lanata",1,41],
    ["Francisco “Paco” Espínola",1,42],
    ["Idea Vilariño",1,43],
    ["Fernando Amado",1,44],
    ["Romero Ghompal",0,45],
    ["Juan J. Mara",0,46],
    ["Alessandra  Rampolla",1,47],
    ["F. Scott Fitzgerald",1,48],
    ["Antonio Varese",0,49],
    ["Jalisco Pérez  Vizcaíno",0,50],
    ["Umberto Eco",1,51],
    ["Mario Vargas Llosa",1,52],
    ["Jaime Sterling",0,53],
    ["Hilario Baderila",0,54],
    ["Ludovica Squirru",1,55],
    ["Clementina Arias",0,56],
    ["Juan Nepomuceno Pesce",0,57],
    ["Danielle Steel",1,58],
    ["Octavio Gorfinkel",0,59],
    ["Tamara Sniegoski",0,60],
    ["Luís Sepúlveda",1,61],
    ["Camilo Also",0,62],
    ["David Hammilt",0,63],
    ["Giorgia Miller",0,64],
    ["Assa Larson",0,65],
    ["Dolores Maude",0,66],
    ["Gabriel García Márquez",1,67],
    ["George Marshall",0,68],
    ["Crystal Parra",0,69],
    ["Elsa Hassle",0,70],
    ["E.L. James",1,71],
    ["Juan L. Grecia",0,72],
    ["Emil Schulz",0,73],
    ["Esteban Berlin",0,74],
    ["Gabriela Mistral",1,75],
    ["Mick Kahuna",0,76],
    ["Lewis Carroll",1,77],
    ["William Faulkner",1,78],
    ["Edith Rosales",0,79],
    ["Len Wewe",0,80],
    ["Roberto Arlt",1,81],
    ["Beatriz Sarlo",1,82],
    ["Rodrigo Fresán",1,83],
    ["Darío Sztajnszrajber",1,84],
    ["Gabriel Goleman",0,85],
    ["Tristán Kunder",0,86],
    ["Emir Faraone",0,87],
    ["Jorge Bucay",1,88],
    ["Tamara Tenenbaum",1,89],
    ["Leila Guerriero",1,90],
    ["Paula Hawkins",1,91],
    ["Cristina Fernández",1,92],
    ["Dolores O'Brien",0,93],
    ["Ingmar Ross",0,94],
    ["María Elena Walsh",1,95],
    ["Indio Solari",1,96],
    ["Helen Velando",1,97],
    ["Tute",1,98],
    ["Ida Vitale",1,99],
    ["Mariano Del Mazo",1,100]
  ]
}
